#!/bin/sh

set -e
set -x

CFLAGS="-gdwarf"

mkdir -p build

rm -f build/*

CFILES=$(cd src && ls *.c)

for file in $CFILES;
do
	./cc $CFLAGS -c -o "build/$file.o" "src/$file"
done

ar rcs libministd.a build/*.c.o
