#!/bin/sh

set -e

./clib 2> /dev/null

CFILES=$(cd test && ls *.c)

for file in $CFILES;
do
	echo -e "COMPILING \033[33m\033[1m$file\033[m..."
	./cc -o "test/$file.o" "test/$file"
done

for file in $CFILES;
do
	echo -e "RUNNING   \033[33m\033[1m$file\033[m..."
	"test/$file.o" > "test/$file.output"
	if diff --color "test/$file.output" "test/$file.expected"; then
		echo -e " === \033[32m\033[1mTEST \033[33m$file\033[32m PASSED\033[m ==="
	else
		echo -e " === \033[31m\033[1mTEST \033[33m$file\033[31m FAILED\033[m ==="
	fi
done
